version: '3.8'

services:
  web:
    build: .
    container_name: vuln_lab_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: vuln_lab_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vulnhospital
      MYSQL_USER: hospitaluser
      MYSQL_PASSWORD: hospitalpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./vulnhospital_database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
